/* lang.js — Language switcher EN/ES/PL/ZH
 * - Legge lingua da localStorage('hdgr-lang'), default 'en'
 * - Applica traduzione a tutti gli elementi [data-i18n="key"]
 * - Salva al click
 */
const TRANSLATIONS = {
  en: {
    /* nav */
    'nav.about': 'About Us',
    'nav.investment': 'Investment Opportunities',
    'nav.news': 'News',
    'nav.contact': 'Contact',
    /* hero */
    'hero.subtitle': 'Design & Development',
    /* services list */
    'services.design': 'Design Services',
    'services.realestate': 'Real Estate Development',
    'services.arch': 'Architectural Projects',
    'services.buyer': 'Buyer Support',
    /* section headers */
    'section.projects': 'Award-Winning Projects',
    'section.projects.arch': 'Architectural Projects',
    'section.about': 'About Us',
    'section.visualizations': 'Visualizations',
    'section.interior': 'Interior Design',
    'section.portfolio': 'Property Portfolio',
    'section.investment': 'Investment Opportunities',
    /* statement */
    'statement.main': 'Design That Lasts, Development That Matters',
    'statement.second': 'We Build What Time Approves',
    /* about */
    'about.intro1': 'We\'re a group of architects and entrepreneurs working across architecture, development, and real estate investment. At HDGR, we keep the entire process in-house, allowing ideas to move quickly from concept to reality. This approach gives us the freedom to question the established rules of the industry and redefine what real estate should be about.',
    'about.intro2': 'At the core of what we do lies our deep belief in timeless architecture and ethical development. We aim to create places that remain beautiful and valuable long after trends pass, working with people who believe that good buildings should age well and matter for decades.',
    /* roles */
    'role.designer': 'Designer',
    'role.business': 'Business Development',
    'role.finance': 'Finance',
    /* project type labels */
    'type.residential': 'Residential',
    'type.public': 'Public',
    'type.public-edu': 'Public / Educational',
    'type.commercial': 'Commercial',
    'type.mixed': 'Mixed Use',
    'type.interior': 'Interior Design',
    'type.interior.residential': 'Residential Interior',
    'type.interior.bathroom': 'Bathroom Interior',
    'type.interior.kitchen': 'Kitchen Interior',
    /* project card composite type+location */
    'slide.nepal.type': 'Nepal — Public',
    'slide.warsaw.residential': 'Warsaw — Residential',
    /* portfolio status */
    'status.available': 'Available',
    'status.sold': 'Sold',
    'status.development': 'In Development',
    /* meta labels */
    'meta.type': 'Type',
    'meta.location': 'Location',
    'meta.area': 'Area',
    'meta.year': 'Year',
    /* labels */
    'label.next-project': 'Next Project',
    /* buttons */
    'btn.all-projects': 'All projects →',
    'btn.go-back': '← Go back',
    'btn.explore': 'Explore',
    'btn.buyer-journey': 'Check Buyer Journey',
    /* footer */
    'footer.touch': 'Get in touch',
    'footer.follow': 'Follow us',
    'footer.contact-btn': 'Contact Our Team',
    /* form */
    'form.firstname': 'First name',
    'form.lastname': 'Last name',
    'form.email': 'Email',
    'form.message': 'Message',
    'form.send': 'Send Inquiry',
    /* investment page */
    'invest.intro': 'Investment structures differ depending on the origin of the investor and the target market. Explore the pathway that fits your case.',
    'invest.tab.eu-eu': 'European investors in EU',
    'invest.tab.latam-eu': 'LatAm investors in EU',
    'invest.tab.asia-eu': 'Asian investors in EU',
    'invest.tab.eu-latam': 'EU investors in LatAm/ASEAN',
    'invest.cta.link': 'Click here',
    'invest.cta.after': ' to explore available opportunities and begin crafting an investment structure tailored to your goals and preferred markets.',
    /* buyer journey steps */
    'buyer.step1.title': 'Selection of Preferred Property',
    'buyer.step1.desc': 'Choose the apartment that best matches your lifestyle, investment goals, and budget. Consider factors such as layout, floor level, views, orientation, and access to building facilities.',
    'buyer.step2.title': 'Sales Consultation',
    'buyer.step2.desc': 'Speak with our sales team to learn more about the project, property specifications, payment structure, and the overall purchasing process.',
    'buyer.step3.title': 'Virtual/Physical Viewing',
    'buyer.step3.desc': 'Attend a virtual tour or schedule an in-person viewing of the property. Explore the building, surrounding neighbourhood, and available amenities.',
    'buyer.step4.title': 'Reservation',
    'buyer.step4.desc': 'Secure your chosen apartment by signing a reservation agreement and paying the initial reservation deposit. This step temporarily removes the property from the market.',
    'buyer.step5.title': 'Initial Documentation',
    'buyer.step5.desc': 'Appoint a lawyer or legal advisor to assist with the transaction. Prepare the required identification and financial documentation, open a local bank account if necessary.',
    'buyer.step6.title': 'Purchase Contract',
    'buyer.step6.desc': 'Sign the private purchase agreement outlining the purchase price, payment method, and conditions of transaction. Complete the agreed deposit payment.',
    'buyer.step7.title': 'Final Signing',
    'buyer.step7.desc': 'Finalize the purchase by signing the official title deed or transfer documents before the relevant legal authority. Transfer the remaining balance to complete the transaction.',
    'buyer.step8.title': 'Property Handover & Ownership Transfer',
    'buyer.step8.desc': 'Receive the keys to your property and the official ownership documentation. Arrange utilities and property management if required.',
    /* project descriptions — Brick House */
    'project.brick-house.desc1': 'Brick House explores compact urban living through a textured masonry shell and carefully framed daylight.',
    'project.brick-house.desc2': 'The plan organizes private and social zones around a central vertical void, balancing density with long-view spatial clarity.',
    /* project descriptions — Microhome */
    'project.microhome.desc1': 'Microhome focuses on essential domestic comfort within a compact footprint, using modular geometry and built-in storage.',
    'project.microhome.desc2': 'Natural light and material continuity extend perceived volume while preserving clear boundaries for work, rest, and gathering.',
    /* project descriptions — Nepal School */
    'project.nepal.desc1': 'A modular building system designed for rural Nepal — locally sourced materials, a repetitive structural frame, adaptable infill. The school grows with the community.',
    'project.nepal.desc2': 'A covered corridor connects classrooms and shared spaces, functioning as both a climatic buffer and an informal social spine — shaded, open, embedded in daily life.',
    /* project descriptions — Beskid Niski */
    'project.beskid.desc1': 'The interior design of this holiday cottage in the Beskid Niski mountains is rooted in the idea of merging contemporary form with the local mountain spirit. The priority was to create a space that feels modern yet close to nature and the atmosphere of the region.',
    'project.beskid.desc2': 'Dominant wood warms the interiors and eases the mind, forming the backbone of the entire composition. Pastel accents in tiles and decorative paints complement the natural base, lending the space lightness and subtle energy. Colour serves both a decorative and symbolic role: bedrooms in yellow and pink create comfort and safety; the bathroom and hallway use green for calm; the kitchen is dominated by blue for cleanliness; the living room holds a neutral palette for quiet rest.',
    'project.beskid.desc3': 'The second floor is an open, multifunctional area combining a recreation zone with a play space for children — a coherent, contemporary interior deeply rooted in the natural character of the Beskid Niski.',
    /* project descriptions — Deante Łazienka */
    'project.deante.desc1': 'The project involved designing a contemporary bathroom using products from Deante and Deante Design Studio, demonstrating that Deante products integrate seamlessly into both classic and modern interiors.',
    'project.deante.desc2': 'Drawing from mid-century modern — a style appreciated for its timeless elegance and harmony of form — the design foregrounds pattern, texture, and colour. Varied materials and shapes are anchored by a deep burgundy tone and light-coloured tiles. A section of wall finished in glass bricks introduces natural, atmospheric light and a sense of subtle asymmetry.',
    /* project descriptions — Gdańsk Lawendowe Wzgórze */
    'project.gdansk.desc1': 'An interior inspired by mid-century modern aesthetics, where warmth meets a touch of character. A palette of brick red, burgundy, and beige builds a cosy, layered atmosphere that envelops the entire space.',
    'project.gdansk.desc2': 'Decorative mouldings on the walls add edge and an elegant rhythm, while modern accents — an organic chrome mirror, minimalist wall lights — introduce a fresh, contemporary twist. Heavy dark curtains and materials of contrasting textures complete the mood, making the space not only stylish but genuinely pleasant to live in.',
    /* project descriptions — Komorów */
    'project.komorow.desc1': 'The kitchen design is built around an ergonomic functional layout and high-quality materials that ensure durability and a timeless character. The island serves as the central workspace, providing a comfortable area for meal preparation and naturally integrating the kitchen with the dining zone.',
    'project.komorow.desc2': 'The introduction of warm-toned wood and cohesive mineral surfaces brings harmony to the interior, while carefully selected task and decorative lighting emphasizes the texture of the materials used. The result is a kitchen that unites everyday comfort, aesthetic balance, and the durability essential for daily life.',
    /* project descriptions — Warszawa Wilanów */
    'project.wilanow.desc1': 'Home is the most important place we have — it\'s where we spend the most time: working, eating, relaxing, and pursuing our passions. An essential quality of any true nest is the warmth that radiates from within, drawing us back and making us want to stay.',
    'project.wilanow.desc2': 'Dark wood and warm beiges envelop the interior, while black minimalist accents give an elegant finish to the walls and ceilings. Green elements — the sofa, the bathroom tiles — bring character and variation to the colour palette.',
  },

  es: {
    'nav.about': 'Sobre Nosotros',
    'nav.investment': 'Oportunidades de Inversión',
    'nav.news': 'Noticias',
    'nav.contact': 'Contacto',
    'hero.subtitle': 'Diseño y Desarrollo',
    'services.design': 'Servicios de Diseño',
    'services.realestate': 'Desarrollo Inmobiliario',
    'services.arch': 'Proyectos Arquitectónicos',
    'services.buyer': 'Apoyo al Comprador',
    'section.projects': 'Proyectos Premiados',
    'section.projects.arch': 'Proyectos Arquitectónicos',
    'section.about': 'Sobre Nosotros',
    'section.visualizations': 'Visualizaciones',
    'section.interior': 'Diseño de Interiores',
    'section.portfolio': 'Cartera de Propiedades',
    'section.investment': 'Oportunidades de Inversión',
    'statement.main': 'Diseño que perdura, desarrollo que importa',
    'statement.second': 'Construimos lo que el tiempo aprueba',
    'about.intro1': 'Somos un grupo de arquitectos y empresarios que trabajan en arquitectura, desarrollo e inversión inmobiliaria. En HDGR, mantenemos todo el proceso internamente, lo que permite que las ideas avancen rápidamente del concepto a la realidad. Este enfoque nos da la libertad de cuestionar las reglas establecidas de la industria y redefinir lo que debería ser el sector inmobiliario.',
    'about.intro2': 'En el núcleo de lo que hacemos reside nuestra profunda creencia en la arquitectura atemporal y el desarrollo ético. Aspiramos a crear lugares que permanezcan bellos y valiosos mucho después de que pasen las tendencias, trabajando con personas que creen que los buenos edificios deben envejecer bien y ser relevantes durante décadas.',
    'role.designer': 'Diseñador/a',
    'role.business': 'Desarrollo de Negocio',
    'role.finance': 'Finanzas',
    'type.residential': 'Residencial',
    'type.public': 'Público',
    'type.public-edu': 'Público / Educativo',
    'type.commercial': 'Comercial',
    'type.mixed': 'Uso Mixto',
    'type.interior': 'Diseño de Interiores',
    'type.interior.residential': 'Interior Residencial',
    'type.interior.bathroom': 'Interior de Baño',
    'type.interior.kitchen': 'Interior de Cocina',
    'slide.nepal.type': 'Nepal — Público',
    'slide.warsaw.residential': 'Warsaw — Residencial',
    'status.available': 'Disponible',
    'status.sold': 'Vendido',
    'status.development': 'En Desarrollo',
    'meta.type': 'Tipo',
    'meta.location': 'Ubicación',
    'meta.area': 'Área',
    'meta.year': 'Año',
    'label.next-project': 'Siguiente Proyecto',
    'btn.all-projects': 'Todos los proyectos →',
    'btn.go-back': '← Volver',
    'btn.explore': 'Explorar',
    'btn.buyer-journey': 'Ver Guía del Comprador',
    'footer.touch': 'Contacto',
    'footer.follow': 'Síguenos',
    'footer.contact-btn': 'Contactar al Equipo',
    'form.firstname': 'Nombre',
    'form.lastname': 'Apellido',
    'form.email': 'Correo electrónico',
    'form.message': 'Mensaje',
    'form.send': 'Enviar Consulta',
    'invest.intro': 'Las estructuras de inversión difieren según el origen del inversor y el mercado objetivo. Explore la vía que se adapta a su caso.',
    'invest.tab.eu-eu': 'Inversores europeos en la UE',
    'invest.tab.latam-eu': 'Inversores latinoamericanos en la UE',
    'invest.tab.asia-eu': 'Inversores asiáticos en la UE',
    'invest.tab.eu-latam': 'Inversores europeos en LatAm/ASEAN',
    'invest.cta.link': 'Haz clic aquí',
    'invest.cta.after': ' para explorar oportunidades disponibles y comenzar a construir una estructura de inversión adaptada a tus objetivos y mercados preferidos.',
    'buyer.step1.title': 'Selección de la Propiedad',
    'buyer.step1.desc': 'Elija el apartamento que mejor se adapte a su estilo de vida, objetivos de inversión y presupuesto. Considere factores como la distribución, el piso, las vistas, la orientación y el acceso a las instalaciones del edificio.',
    'buyer.step2.title': 'Consulta de Ventas',
    'buyer.step2.desc': 'Hable con nuestro equipo de ventas para obtener más información sobre el proyecto, las especificaciones de la propiedad, la estructura de pago y el proceso general de compra.',
    'buyer.step3.title': 'Visita Virtual/Presencial',
    'buyer.step3.desc': 'Asista a un recorrido virtual o programe una visita en persona. Explore el edificio, el barrio circundante y los servicios disponibles.',
    'buyer.step4.title': 'Reserva',
    'buyer.step4.desc': 'Asegure su apartamento elegido firmando un contrato de reserva y pagando el depósito inicial. Este paso retira temporalmente la propiedad del mercado.',
    'buyer.step5.title': 'Documentación Inicial',
    'buyer.step5.desc': 'Contrate un abogado para que le asesore en la transacción. Prepare la documentación de identificación y financiera requerida, y abra una cuenta bancaria local si es necesario.',
    'buyer.step6.title': 'Contrato de Compra',
    'buyer.step6.desc': 'Firme el contrato privado de compra donde se indican el precio, el método de pago y las condiciones de la transacción. Complete el pago del depósito acordado.',
    'buyer.step7.title': 'Firma Final',
    'buyer.step7.desc': 'Finalice la compra firmando la escritura oficial de propiedad ante la autoridad legal correspondiente. Transfiera el saldo restante para completar la transacción.',
    'buyer.step8.title': 'Entrega y Transferencia de Titularidad',
    'buyer.step8.desc': 'Reciba las llaves de su propiedad y la documentación oficial de propiedad. Gestione los servicios públicos y la administración de la propiedad si es necesario.',
    'project.brick-house.desc1': 'Brick House explora la vida urbana compacta mediante una fachada de mampostería texturizada y la luz natural cuidadosamente encuadrada.',
    'project.brick-house.desc2': 'La planta organiza zonas privadas y sociales alrededor de un vacío vertical central, equilibrando la densidad con la claridad espacial de largo alcance.',
    'project.microhome.desc1': 'Microhome se centra en el confort doméstico esencial dentro de una planta compacta, utilizando geometría modular y almacenamiento integrado.',
    'project.microhome.desc2': 'La luz natural y la continuidad de materiales amplían el volumen percibido mientras se mantienen límites claros para el trabajo, el descanso y la reunión.',
    'project.nepal.desc1': 'Nepal School es una instalación educativa pública diseñada para una comunidad de montaña remota, priorizando la resiliencia estructural, la luz natural y métodos de construcción de baja tecnología.',
    'project.nepal.desc2': 'El proyecto negocia una topografía empinada y cadenas de suministro de materiales limitadas mediante una distribución compacta que maximiza el área útil minimizando la alteración del terreno.',
    'project.beskid.desc1': 'El diseño de interiores de esta cabaña vacacional en las montañas de Beskid Niski se basa en la idea de fusionar la forma contemporánea con el espíritu de la montaña local. La prioridad era crear un espacio que se sintiera moderno pero cercano a la naturaleza y la atmósfera de la región.',
    'project.beskid.desc2': 'La madera dominante calienta los interiores y relaja la mente, formando la columna vertebral de toda la composición. Los acentos en tonos pastel en azulejos y pinturas decorativas complementan la base natural, dando al espacio ligereza y una energía sutil. El color desempeña un papel tanto decorativo como simbólico: los dormitorios en amarillo y rosa crean comodidad y seguridad; el baño y el pasillo usan el verde para la calma; la cocina está dominada por el azul para la limpieza; el salón tiene una paleta neutra para el descanso tranquilo.',
    'project.beskid.desc3': 'La segunda planta es un área abierta y multifuncional que combina una zona de recreación con un espacio de juego para niños — un interior coherente y contemporáneo profundamente enraizado en el carácter natural del Beskid Niski.',
    'project.deante.desc1': 'El proyecto consistió en diseñar un baño contemporáneo con productos de Deante y Deante Design Studio, demostrando que los productos Deante se integran perfectamente en interiores tanto clásicos como modernos.',
    'project.deante.desc2': 'Inspirado en el mid-century modern — un estilo apreciado por su elegancia atemporal y armonía de formas — el diseño da protagonismo al patrón, la textura y el color. Los materiales y formas variados están anclados por un tono burdeos intenso y azulejos de colores claros. Una sección de pared acabada en ladrillos de vidrio introduce luz natural y atmosférica y una sensación de sutil asimetría.',
    'project.gdansk.desc1': 'Un interior inspirado en la estética del mid-century modern, donde el calor se encuentra con un toque de carácter. Una paleta de rojo ladrillo, burdeos y beige crea una atmósfera acogedora y estratificada que envuelve todo el espacio.',
    'project.gdansk.desc2': 'Las molduras decorativas en las paredes añaden dinamismo y un ritmo elegante, mientras que los acentos modernos — un espejo cromado orgánico, apliques minimalistas — introducen un toque fresco y contemporáneo. Las cortinas oscuras pesadas y los materiales de texturas contrastantes completan el ambiente, haciendo el espacio no solo elegante sino genuinamente agradable para vivir.',
    'project.komorow.desc1': 'El diseño de la cocina se basa en una distribución funcional ergonómica y materiales de alta calidad que garantizan durabilidad y un carácter atemporal. La isla sirve como espacio de trabajo central, proporcionando un área cómoda para la preparación de comidas e integrando naturalmente la cocina con la zona de comedor.',
    'project.komorow.desc2': 'La introducción de madera de tonos cálidos y superficies minerales cohesionadas aporta armonía al interior, mientras que la iluminación funcional y decorativa cuidadosamente seleccionada destaca la textura de los materiales utilizados. El resultado es una cocina que une el confort cotidiano, el equilibrio estético y la durabilidad esencial para la vida diaria.',
    'project.wilanow.desc1': 'El hogar es el lugar más importante que tenemos — es donde pasamos más tiempo: trabajando, comiendo, relajándonos y desarrollando nuestras pasiones. Una cualidad esencial de cualquier verdadero hogar es el calor que irradia desde dentro, que nos atrae de vuelta y nos hace querer quedarnos.',
    'project.wilanow.desc2': 'La madera oscura y los beiges cálidos envuelven el interior, mientras que los acentos minimalistas en negro dan un acabado elegante a las paredes y techos. Los elementos verdes — el sofá, los azulejos del baño — aportan carácter y variación a la paleta de colores.',
  },

  pl: {
    'nav.about': 'O Nas',
    'nav.investment': 'Możliwości Inwestycyjne',
    'nav.news': 'Aktualności',
    'nav.contact': 'Kontakt',
    'hero.subtitle': 'Projekt i Rozwój',
    'services.design': 'Usługi Projektowe',
    'services.realestate': 'Deweloperka Nieruchomości',
    'services.arch': 'Projekty Architektoniczne',
    'services.buyer': 'Wsparcie Kupującego',
    'section.projects': 'Nagradzane Projekty',
    'section.projects.arch': 'Projekty Architektoniczne',
    'section.about': 'O Nas',
    'section.visualizations': 'Wizualizacje',
    'section.interior': 'Projektowanie Wnętrz',
    'section.portfolio': 'Portfolio Nieruchomości',
    'section.investment': 'Możliwości Inwestycyjne',
    'statement.main': 'Projekt na lata, rozwój który ma znaczenie',
    'statement.second': 'Budujemy to, co przetrwa próbę czasu',
    'about.intro1': 'Jesteśmy grupą architektów i przedsiębiorców działających w obszarze architektury, developmentu i inwestycji w nieruchomości. W HDGR realizujemy cały proces wewnętrznie, dzięki czemu pomysły szybko przechodzą od koncepcji do rzeczywistości. Takie podejście daje nam swobodę kwestionowania ustalonych reguł branży i redefiniowania tego, czym powinny być nieruchomości.',
    'about.intro2': 'U podstaw naszej działalności leży głębokie przekonanie o wartości ponadczasowej architektury i etycznego developmentu. Dążymy do tworzenia miejsc, które pozostają piękne i wartościowe na długo po tym, jak mody przeminą — współpracując z ludźmi wierzącymi, że dobre budynki powinny dobrze się starzeć i mieć znaczenie przez dziesięciolecia.',
    'role.designer': 'Projektant/ka',
    'role.business': 'Rozwój Biznesu',
    'role.finance': 'Finanse',
    'type.residential': 'Mieszkalny',
    'type.public': 'Publiczny',
    'type.public-edu': 'Publiczny / Edukacyjny',
    'type.commercial': 'Komercyjny',
    'type.mixed': 'Mieszany',
    'type.interior': 'Projektowanie Wnętrz',
    'type.interior.residential': 'Wnętrze Mieszkalne',
    'type.interior.bathroom': 'Wnętrze Łazienki',
    'type.interior.kitchen': 'Wnętrze Kuchni',
    'slide.nepal.type': 'Nepal — Publiczny',
    'slide.warsaw.residential': 'Warszawa — Mieszkalny',
    'status.available': 'Dostępny',
    'status.sold': 'Sprzedany',
    'status.development': 'W budowie',
    'meta.type': 'Typ',
    'meta.location': 'Lokalizacja',
    'meta.area': 'Powierzchnia',
    'meta.year': 'Rok',
    'label.next-project': 'Następny projekt',
    'btn.all-projects': 'Wszystkie projekty →',
    'btn.go-back': '← Wróć',
    'btn.explore': 'Odkryj',
    'btn.buyer-journey': 'Przewodnik Kupującego',
    'footer.touch': 'Skontaktuj się',
    'footer.follow': 'Obserwuj nas',
    'footer.contact-btn': 'Skontaktuj się z Zespołem',
    'form.firstname': 'Imię',
    'form.lastname': 'Nazwisko',
    'form.email': 'E-mail',
    'form.message': 'Wiadomość',
    'form.send': 'Wyślij Zapytanie',
    'invest.intro': 'Struktury inwestycyjne różnią się w zależności od pochodzenia inwestora i rynku docelowego. Poznaj ścieżkę dopasowaną do Twojego przypadku.',
    'invest.tab.eu-eu': 'Inwestorzy europejscy w UE',
    'invest.tab.latam-eu': 'Inwestorzy z Ameryki Łacińskiej w UE',
    'invest.tab.asia-eu': 'Inwestorzy azjatyccy w UE',
    'invest.tab.eu-latam': 'Inwestorzy z UE w LatAm/ASEAN',
    'invest.cta.link': 'Kliknij tutaj',
    'invest.cta.after': ', aby zapoznać się z dostępnymi możliwościami i zacząć tworzyć strukturę inwestycyjną dopasowaną do Twoich celów i preferowanych rynków.',
    'buyer.step1.title': 'Wybór preferowanej nieruchomości',
    'buyer.step1.desc': 'Wybierz mieszkanie, które najlepiej odpowiada Twojemu stylowi życia, celom inwestycyjnym i budżetowi. Weź pod uwagę takie czynniki jak układ, piętro, widoki, orientacja i dostęp do udogodnień budynku.',
    'buyer.step2.title': 'Konsultacja sprzedażowa',
    'buyer.step2.desc': 'Porozmawiaj z naszym zespołem sprzedaży, aby dowiedzieć się więcej o projekcie, specyfikacji nieruchomości, strukturze płatności i ogólnym procesie zakupu.',
    'buyer.step3.title': 'Wizyta wirtualna/osobista',
    'buyer.step3.desc': 'Weź udział w wirtualnym spacerze lub zaplanuj wizytę osobistą. Poznaj budynek, okoliczną dzielnicę i dostępne udogodnienia.',
    'buyer.step4.title': 'Rezerwacja',
    'buyer.step4.desc': 'Zabezpiecz wybrane mieszkanie, podpisując umowę rezerwacyjną i wpłacając wstępną kaucję. Ten krok tymczasowo wycofuje nieruchomość z rynku.',
    'buyer.step5.title': 'Dokumentacja wstępna',
    'buyer.step5.desc': 'Zatrudnij prawnika lub doradcę prawnego do pomocy w transakcji. Przygotuj wymagane dokumenty identyfikacyjne i finansowe, a w razie potrzeby otwórz lokalne konto bankowe.',
    'buyer.step6.title': 'Umowa przedwstępna',
    'buyer.step6.desc': 'Podpisz prywatną umowę kupna określającą cenę zakupu, sposób płatności i warunki transakcji. Dokonaj uzgodnionej wpłaty zaliczki.',
    'buyer.step7.title': 'Podpisanie aktu notarialnego',
    'buyer.step7.desc': 'Sfinalizuj zakup, podpisując oficjalny akt własności przed właściwym organem prawnym. Przelej pozostałe saldo, aby zakończyć transakcję.',
    'buyer.step8.title': 'Przekazanie nieruchomości i przeniesienie własności',
    'buyer.step8.desc': 'Odbierz klucze do swojej nieruchomości oraz oficjalną dokumentację własności. W razie potrzeby zorganizuj media i zarządzanie nieruchomością.',
    'project.brick-house.desc1': 'Brick House bada kompaktowe mieszkalnictwo miejskie poprzez teksturowaną okładzinę murową i starannie kadrowane naturalne światło.',
    'project.brick-house.desc2': 'Rzut organizuje strefy prywatne i społeczne wokół centralnego pionowego pustostanu, balansując gęstość z przestrzenną przejrzystością dalekosiężnych widoków.',
    'project.microhome.desc1': 'Microhome skupia się na podstawowym komforcie domowym w kompaktowym obrysie, wykorzystując geometrię modułową i wbudowane schowki.',
    'project.microhome.desc2': 'Naturalne światło i ciągłość materiałów rozszerzają odczuwaną przestrzeń, zachowując jednocześnie wyraźne strefy do pracy, odpoczynku i spotkań.',
    'project.nepal.desc1': 'Nepal School to publiczna placówka oświatowa zaprojektowana dla odległej górskiej społeczności, stawiająca na odporność konstrukcji, naturalne światło i metody budowy niskonakładowe.',
    'project.nepal.desc2': 'Projekt mierzy się ze stromą topografią i ograniczonymi łańcuchami dostaw materiałów poprzez kompaktowy układ maksymalizujący użytkową powierzchnię przy minimalnej ingerencji w teren.',
    'project.beskid.desc1': 'Projekt wnętrza tej chatki wypoczynkowej w Beskidzie Niskim opiera się na idei połączenia formy współczesnej z lokalnym duchem gór. Priorytetem było stworzenie przestrzeni nowoczesnej, a zarazem bliskiej naturze i atmosferze regionu.',
    'project.beskid.desc2': 'Dominujące drewno ogrzewa wnętrza i uspokaja umysł, stanowiąc kręgosłup całej kompozycji. Pastelowe akcenty w płytkach i farbach dekoracyjnych uzupełniają naturalną bazę, nadając przestrzeni lekkość i subtelną energię. Kolor pełni zarówno rolę dekoracyjną, jak i symboliczną: sypialnie w żółciach i różach tworzą komfort i bezpieczeństwo; łazienka i korytarz używają zieleni dla spokoju; w kuchni dominuje niebieski dla czystości; salon utrzymuje neutralną paletę dla cichego odpoczynku.',
    'project.beskid.desc3': 'Drugie piętro to otwarta, wielofunkcyjna przestrzeń łącząca strefę rekreacji z miejscem zabaw dla dzieci — spójne, współczesne wnętrze głęboko zakorzenione w naturalnym charakterze Beskidu Niskiego.',
    'project.deante.desc1': 'Projekt polegał na zaprojektowaniu nowoczesnej łazienki z produktami Deante i Deante Design Studio, pokazując, że produkty Deante płynnie wpisują się zarówno w klasyczne, jak i nowoczesne wnętrza.',
    'project.deante.desc2': 'Czerpiąc z estetyki mid-century modern — stylu cenionego za ponadczasową elegancję i harmonię formy — projekt eksponuje wzór, fakturę i kolor. Zróżnicowane materiały i kształty zakotwiczone są w głębokim bordowym odcieniu i jasnych płytkach. Fragment ściany wykończony cegłą szklaną wprowadza naturalne, nastrojowe światło i poczucie subtelnej asymetrii.',
    'project.gdansk.desc1': 'Wnętrze inspirowane estetyką mid-century modern, gdzie ciepło spotyka się z odrobiną charakteru. Paleta ciemnej cegły, bordo i beżu tworzy przytulną, warstwową atmosferę owijającą całą przestrzeń.',
    'project.gdansk.desc2': 'Dekoracyjne sztukaterie na ścianach dodają wyrazistości i eleganckiego rytmu, podczas gdy nowoczesne akcenty — organiczne chromowane lustro, minimalistyczne kinkiety — wprowadzają świeże, współczesne nuty. Ciężkie ciemne zasłony i materiały o kontrastujących fakturach dopełniają nastrój, czyniąc przestrzeń nie tylko stylową, ale naprawdę przyjemną do życia.',
    'project.komorow.desc1': 'Projekt kuchni oparty jest na ergonomicznym układzie funkcjonalnym i wysokiej jakości materiałach zapewniających trwałość i ponadczasowy charakter. Wyspa stanowi centralne miejsce pracy, zapewniając wygodną przestrzeń do przygotowywania posiłków i naturalnie łącząc kuchnię ze strefą jadalną.',
    'project.komorow.desc2': 'Wprowadzenie drewna w ciepłych odcieniach i spójnych mineralnych powierzchni wnosi harmonię do wnętrza, a starannie dobrane oświetlenie robocze i dekoracyjne podkreśla fakturę użytych materiałów. Efektem jest kuchnia łącząca codzienny komfort, estetyczną równowagę i trwałość niezbędną w codziennym życiu.',
    'project.wilanow.desc1': 'Dom to najważniejsze miejsce, jakie mamy — tu spędzamy najwięcej czasu: pracując, jedząc, odpoczywając i realizując pasje. Niezbędną cechą każdego prawdziwego gniazda jest ciepło, które emanuje z jego wnętrza, przyciągając nas z powrotem i sprawiając, że chcemy zostać.',
    'project.wilanow.desc2': 'Ciemne drewno i ciepłe beże otulają wnętrze, a czarne minimalistyczne akcenty nadają ścianom i sufitom eleganckie wykończenie. Zielone elementy — sofa, płytki w łazience — wnoszą charakter i różnorodność do palety barw.',
  },

  zh: {
    'nav.about': '关于我们',
    'nav.investment': '投资机会',
    'nav.news': '新闻',
    'nav.contact': '联系',
    'hero.subtitle': '设计与开发',
    'services.design': '设计服务',
    'services.realestate': '房地产开发',
    'services.arch': '建筑项目',
    'services.buyer': '买家支持',
    'section.projects': '获奖项目',
    'section.projects.arch': '建筑项目',
    'section.about': '关于我们',
    'section.visualizations': '可视化',
    'section.interior': '室内设计',
    'section.portfolio': '房产组合',
    'section.investment': '投资机会',
    'statement.main': '经久设计，有意开发',
    'statement.second': '我们建造经得起时间考验的作品',
    'about.intro1': '我们是一支由建筑师和企业家组成的团队，专注于建筑设计、开发及房地产投资。在HDGR，我们将整个流程保持在内部，使创意能够快速从概念转化为现实。这种方式赋予我们自由，去质疑行业既定规则，重新定义房地产的意义。',
    'about.intro2': '我们工作的核心是对永恒建筑和道德开发的深切信念。我们致力于创造在潮流消逝后仍保持美丽和价值的场所，与那些相信优秀建筑应该随时间老化、数十年仍具意义的人们合作。',
    'role.designer': '设计师',
    'role.business': '业务发展',
    'role.finance': '财务',
    'type.residential': '住宅',
    'type.public': '公共',
    'type.public-edu': '公共 / 教育',
    'type.commercial': '商业',
    'type.mixed': '混合用途',
    'type.interior': '室内设计',
    'type.interior.residential': '住宅室内',
    'type.interior.bathroom': '浴室室内',
    'type.interior.kitchen': '厨房室内',
    'slide.nepal.type': '尼泊尔 — 公共',
    'slide.warsaw.residential': '华沙 — 住宅',
    'status.available': '可购',
    'status.sold': '已售',
    'status.development': '开发中',
    'meta.type': '类型',
    'meta.location': '地点',
    'meta.area': '面积',
    'meta.year': '年份',
    'label.next-project': '下一个项目',
    'btn.all-projects': '所有项目 →',
    'btn.go-back': '← 返回',
    'btn.explore': '探索',
    'btn.buyer-journey': '买家指南',
    'footer.touch': '联系我们',
    'footer.follow': '关注我们',
    'footer.contact-btn': '联系团队',
    'form.firstname': '名字',
    'form.lastname': '姓氏',
    'form.email': '电子邮件',
    'form.message': '留言',
    'form.send': '发送咨询',
    'invest.intro': '投资结构因投资者来源和目标市场而异。探索适合您情况的途径。',
    'invest.tab.eu-eu': '欧洲投资者在欧盟',
    'invest.tab.latam-eu': '拉美投资者在欧盟',
    'invest.tab.asia-eu': '亚洲投资者在欧盟',
    'invest.tab.eu-latam': '欧盟投资者在拉美/东盟',
    'invest.cta.link': '点击此处',
    'invest.cta.after': '，探索可用机会，开始制定符合您目标和首选市场的投资结构。',
    'buyer.step1.title': '选择心仪房产',
    'buyer.step1.desc': '选择最符合您生活方式、投资目标和预算的公寓。考虑户型、楼层、视野、朝向以及楼内设施等因素。',
    'buyer.step2.title': '销售咨询',
    'buyer.step2.desc': '与我们的销售团队交流，了解项目详情、房产规格、付款方式及整体购买流程。',
    'buyer.step3.title': '线上/线下看房',
    'buyer.step3.desc': '参加虚拟导览或预约实地看房，探索楼栋、周边环境及可用设施。',
    'buyer.step4.title': '预订',
    'buyer.step4.desc': '签署预订协议并支付初始预订定金，确保您选择的公寓。此步骤将暂时将该房产从市场下架。',
    'buyer.step5.title': '初步文件准备',
    'buyer.step5.desc': '聘请律师或法律顾问协助交易。准备所需的身份证明和财务文件，如有必要请开立本地银行账户。',
    'buyer.step6.title': '购买合同',
    'buyer.step6.desc': '签署明确购买价格、付款方式和交易条件的私人购买协议，并完成约定的定金支付。',
    'buyer.step7.title': '最终签约',
    'buyer.step7.desc': '在相关法律机构前签署官方产权证书或转让文件，完成购房手续。转账剩余款项以完成交易。',
    'buyer.step8.title': '房产交付及产权转移',
    'buyer.step8.desc': '领取您的房产钥匙及官方产权文件。如有需要，安排水电煤及物业管理事宜。',
    'project.brick-house.desc1': 'Brick House通过纹理砌体外壳和精心取景的自然光，探索紧凑的城市居住方式。',
    'project.brick-house.desc2': '平面图围绕中央垂直空洞组织私密区和社交区，在密度与长视野空间清晰度之间取得平衡。',
    'project.microhome.desc1': 'Microhome专注于在紧凑的占地面积内实现基本的家居舒适，采用模块化几何和内置储物。',
    'project.microhome.desc2': '自然光和材料连续性延伸了感知体量，同时为工作、休息和聚会保留了清晰的边界。',
    'project.nepal.desc1': '尼泊尔学校是为偏远山区社区设计的公共教育设施，优先考虑结构韧性、自然采光和低技术建造方法。',
    'project.nepal.desc2': '项目通过紧凑的布局应对陡峭地形和有限的材料供应链，最大化可用建筑面积，同时最小化对场地的干扰。',
    'project.beskid.desc1': '这座位于Beskid Niski山区度假小屋的室内设计，根植于将当代形式与当地山地精神融合的理念。首要目标是创造一个既现代又贴近自然和地域氛围的空间。',
    'project.beskid.desc2': '占主导的木材温暖室内空间、抚慰心灵，构成整体构图的骨架。瓷砖和装饰涂料中的柔和色调点缀自然底色，赋予空间轻盈感和微妙活力。色彩兼具装饰和象征意义：黄色和粉色卧室营造舒适与安全感；浴室和走廊用绿色带来平静；厨房以蓝色彰显洁净；客厅保持中性调色板以安静休息。',
    'project.beskid.desc3': '二楼是一个开放的多功能区域，将休闲区与儿童游乐空间相结合——一个深深扎根于Beskid Niski自然特性的连贯当代室内。',
    'project.deante.desc1': '该项目使用Deante和Deante Design Studio的产品设计了一个当代浴室，展示了Deante产品能够无缝融入经典和现代室内的能力。',
    'project.deante.desc2': '从中世纪现代主义汲取灵感——这一风格以其永恒的优雅和形式和谐而受到赞赏——设计突出了图案、纹理和色彩。多样的材料和形状以深勃艮第色调和浅色瓷砖为基础。一段玻璃砖完成的墙面带来了自然、大气的光线和微妙不对称感。',
    'project.gdansk.desc1': '受中世纪现代美学启发的室内空间，温暖与个性在此交融。砖红、勃艮第和米色调色板构建了一种温馨、层次丰富的氛围，笼罩整个空间。',
    'project.gdansk.desc2': '墙面装饰线条增添了质感和优雅节奏，而现代元素——有机铬镜、极简壁灯——带来清新的当代气息。厚重的深色窗帘和对比纹理材料完善了整体氛围，使空间不仅时尚，而且真正令人愉悦。',
    'project.komorow.desc1': '厨房设计以符合人体工学的功能布局和高品质材料为核心，确保耐用性和永恒特质。岛台作为中心工作区，提供了舒适的备餐空间，并自然地将厨房与餐厅区相连。',
    'project.komorow.desc2': '引入暖色调木材和整体矿物表面为室内带来和谐感，而精心挑选的功能性和装饰性照明强调了所用材料的纹理。成果是一个将日常舒适、美学平衡与日常生活所需耐用性融为一体的厨房。',
    'project.wilanow.desc1': '家是我们最重要的地方——我们在这里花费最多时间：工作、用餐、休息、追求热情。任何真正巢穴的基本特质，是从内部散发的温暖，吸引我们回来并让我们想要留下。',
    'project.wilanow.desc2': '深色木材和温暖米色包裹室内空间，黑色极简元素为墙壁和天花板带来优雅的收尾。绿色元素——沙发、浴室瓷砖——为调色板带来个性和变化。',
  }
};

(function() {
  function getLang() {
    return localStorage.getItem('hdgr-lang') || 'en';
  }

  function applyLang(lang) {
    const t = TRANSLATIONS[lang] || TRANSLATIONS.en;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (t[key]) el.textContent = t[key];
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      if (t[key]) el.placeholder = t[key];
    });
    document.documentElement.setAttribute('data-lang', lang);
    document.documentElement.setAttribute('lang', lang === 'zh' ? 'zh-CN' : lang);
    const btn = document.querySelector('.lang-current');
    if (btn) btn.textContent = lang.toUpperCase();
  }

  function init() {
    const lang = getLang();
    applyLang(lang);

    const switcher = document.querySelector('.lang-switcher');
    if (!switcher) return;

    const current = switcher.querySelector('.lang-current');
    const dropdown = switcher.querySelector('.lang-dropdown');

    current.addEventListener('click', (e) => {
      e.stopPropagation();
      dropdown.classList.toggle('is-open');
    });

    switcher.querySelectorAll('[data-lang-option]').forEach(item => {
      item.addEventListener('click', () => {
        const selected = item.getAttribute('data-lang-option');
        localStorage.setItem('hdgr-lang', selected);
        applyLang(selected);
        dropdown.classList.remove('is-open');
      });
    });

    document.addEventListener('click', () => dropdown.classList.remove('is-open'));
  }

  document.addEventListener('DOMContentLoaded', init);
})();
